spring:
  datasource:
    username: root
    password: hage1234
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://47.105.69.171:3306/shiyanlou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver