logging:
  level:
    com.example: TRACE
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.69.171:3306/shiyanlou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: hage1234
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiyanlou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
# Mybatis配置
mybatis:
  # XML扫描路径
  mapper-locations: classpath:mapper/*Mapper.xml
  # 配置别名包
  type-aliases-package: com.example.entity
  # 通用Mapper的方法会自动转换驼峰，但手写的SQL需要开启才能转换
  configuration:
    map-underscore-to-camel-case: on
# 通用Mapper配置
mapper:
  # 对于一般的getAllIfColumnNode，是否判断!=''，默认不判断
  not-empty: false
  # 主键自增回写方法,默认值MYSQL,详细说明请看官方文档
  identity: MYSQL
# PageHelper配置
pagehelper:
  #指定Mysql分页方式
  helperDialect: mysql
  #分页合理化参数，pageNum<=0 时会查询第一页
  #pageNum>pages（超过总数时），会查询最后一页。
  reasonable: true
# 打印SQL
logging:
  level:
    com.example: TRACE